# Generated by Django 4.1 on 2022-10-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_alter_employee_emp_id_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp600', max_length=70),
        ),
    ]
