# Generated by Django 4.1 on 2022-10-07 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_rename_nuban_employee_account_alter_employee_emp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('basic_salary', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('days', models.PositiveIntegerField(default=0)),
                ('gross_salary', models.PositiveIntegerField(default=0)),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.payslip')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp281', max_length=70),
        ),
        migrations.DeleteModel(
            name='Kin',
        ),
    ]
