# Generated by Django 4.1 on 2022-10-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0006_alter_employee_emp_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payslip',
            new_name='breakdown',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp122', max_length=70),
        ),
    ]
