# Generated by Django 4.1 on 2022-10-07 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0010_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hrms.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp930', max_length=70),
        ),
    ]
