# Generated by Django 4.1 on 2022-10-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0013_remove_payslip_first_name_remove_payslip_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payslip',
            old_name='days',
            new_name='number_of_days_present',
        ),
        migrations.AddField(
            model_name='payslip',
            name='net_salary',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='working_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp453', max_length=70),
        ),
    ]
