# Generated by Django 4.1 on 2022-10-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0014_rename_days_payslip_number_of_days_present_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp243', max_length=70),
        ),
    ]
