# Generated by Django 4.1 on 2022-10-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0015_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp371', max_length=70),
        ),
    ]
