# Generated by Django 4.1 on 2022-10-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0020_alter_employee_emp_id_alter_payslip_csg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp913', max_length=70),
        ),
    ]
